# Generated by Django 2.2 on 2021-01-29 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviedetails',
            name='movie_id',
            field=models.CharField(max_length=100),
        ),
    ]
