# Generated by Django 2.2 on 2021-01-29 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210129_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviedetails',
            name='rating',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
